### PR TITLE
Solve the build issue on Windows

### PR DESCRIPTION
**Pull request by rovinyu**

### CODE REVIEW

**Comment by parai** [comment]
Hi @rovinyu 👍 
Thanks for this PR, but ssas-public is not intended to be free if you check the README.
And the ssas-public is a place for me to demonstrate those AUTOSAR modules developed by me and this is not the original repo, and I will sell those modules for commercial purpose. So generally, I am the only maintainer and developer for this repo.

But anyway, thanks your contributions.

**Comment by parai** [comment]
Hi @rovinyu 👍 
Thanks for this PR, but ssas-public is not intended to be free if you check the README.
And the ssas-public is a place for me to demonstrate those AUTOSAR modules developed by me and this is not the original repo, and I will sell those modules for commercial purpose. So generally, I am the only maintainer and developer for this repo.

But anyway, thanks your contributions.

**Comment by parai** [comment]
PR is not accepted as copyright and commercial reasons.
Sorry.

**Comment by MasakatsuFunaki** [comment]
> Hi @rovinyu 👍 Thanks for this PR, but ssas-public is not intended to be free if you check the README. And the ssas-public is a place for me to demonstrate those AUTOSAR modules developed by me and this is not the original repo, and I will sell those modules for commercial purpose. So generally, I am the only maintainer and developer for this repo.
> 
> But anyway, thanks your contributions.

are you serious ? autosar implementations cannot be used commercially by private individuals without an AUTOSAR membership and license for commercial explitation

**Pull request closed without merging**
